tone1 <- read.table("result1.txt", header = TRUE, sep = " ")
plot(1,type='n',xlim=c(1,max(tone1$Frequency)),ylim=c(0, max(tone1$Magnitude)),xlab='Frequency', ylab='magnitude', main='tone1')
lines(tone1$Frequency,tone1$Magnitude,type='o',col='olivedrab',lwd=1)
tone2 <- read.table("result2.txt", header = TRUE, sep = " ")
plot(1,type='n',xlim=c(1,max(tone2$Frequency)),ylim=c(0, max(tone2$Magnitude)),xlab='Frequency', ylab='magnitude', main='tone2')
lines(tone2$Frequency,tone2$Magnitude,type='o',col='olivedrab',lwd=1)
tone3 <- read.table("result3.txt", header = TRUE, sep = " ")
plot(1,type='n',xlim=c(1,max(tone3$Frequency)),ylim=c(0, max(tone3$Magnitude)),xlab='Frequency', ylab='magnitude', main='tone3')
lines(tone3$Frequency,tone3$Magnitude,type='o',col='olivedrab',lwd=1)
tone4 <- read.table("result4.txt", header = TRUE, sep = " ")
plot(1,type='n',xlim=c(1,max(tone4$Frequency)),ylim=c(0, max(tone4$Magnitude)),xlab='Frequency', ylab='magnitude', main='tone4')
lines(tone4$Frequency,tone4$Magnitude,type='o',col='olivedrab',lwd=1)
tone5 <- read.table("result5.txt", header = TRUE, sep = " ")
plot(1,type='n',xlim=c(1,max(tone5$Frequency)),ylim=c(0, max(tone5$Magnitude)),xlab='Frequency', ylab='magnitude', main='tone5')
lines(tone5$Frequency,tone5$Magnitude,type='o',col='olivedrab',lwd=1)
tone6 <- read.table("result6.txt", header = TRUE, sep = " ")
plot(1,type='n',xlim=c(1,max(tone6$Frequency)),ylim=c(0, max(tone6$Magnitude)),xlab='Frequency', ylab='magnitude', main='tone6')
lines(tone6$Frequency,tone6$Magnitude,type='o',col='olivedrab',lwd=1)
tone7 <- read.table("result7.txt", header = TRUE, sep = " ")
plot(1,type='n',xlim=c(1,max(tone7$Frequency)),ylim=c(0, max(tone7$Magnitude)),xlab='Frequency', ylab='magnitude', main='tone7')
lines(tone7$Frequency,tone7$Magnitude,type='o',col='olivedrab',lwd=1)
